[package]
name = "NyauxKT"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.6.0"
flanterm_bindings = "1.1.3"
limine = "0.3.1"
owo-colors = "4.1.0"
spin = "0.9.8"

[profile.release]
debug = true
